# Copyright (c) 2023 Boston Dynamics AI Institute LLC. All rights reserved.

model_filename: dexterity/models/xml/scenes/legacy/box_push_2d.xml

vis:
  filename: dexterity/models/xml/scenes/legacy/box_push_2d.yml
  indices: ([0, 1, 0])
  scale: ([1, 1, 0.0])

action:
  bound_lower: ([-3.5, -1.5])
  bound_upper: -self.action_bound_lower
  range: torch.ones_like(self.action_bound_lower) * 2
  types: "[AT.RANGED, AT.PROXIMITY, AT.CONTINUATION, AT.GOAL]"
  distribution: ([6, 2, 2, 1])

reward:
  distance_scaling: ([1, 1, 0, 0, 0.1, 0.1, 0, 0])
  proximity_scaling: 0.001
  reachability_scaling: 0.001

start:
  state:       ([2.0,    0,  0.0,    0, 0, 0, 0, 0])
  bound_lower: ([1.5, -0.5, -0.5, -0.5, 0, 0, 0, 0])
  bound_upper: ([2.5,  0.5,  0.5,  0.5, 0, 0, 0, 0])
goal:
  state:       ([-2.0,    0, 0, 0, 0, 0, 0, 0])
  bound_lower: ([-2.5, -0.5, 0, 0, 0, 0, 0, 0])
  bound_upper: ([-1.5,  0.5, 0, 0, 0, 0, 0, 0])

learner:
  early_stop: 1.0
  trajectory_length: 100
  use_sparse_reward: True
  final_success_distance: 0.05
  stop_converged_injection: False
  max_planner_experience_share: 0.5

intermediate_pruning: False
num_sub_goals: 30
steps_per_goal: 30
goal_bias: 0.0
termination_distance: 0.0
max_main_nodes: 50000
action_time_step: 0.4
action_steps_max: 3

seed: 0
