# Copyright (c) 2023 Boston Dynamics AI Institute LLC. All rights reserved.

model_filename: dexterity/models/xml/scenes/legacy/bimanual_station.xml

start:
  state: ([0.6, 0, 0.251, 1, 0, 0, 0, 0, 0.8, 0, -1.6, 0, 0, 0, 0, 0.8, 0, -1.6, 0, 0, 0] + [0.0] * 20)
goal:
  state: ([0.6, 0, 0.251, np.cos(np.pi / 2), 0, np.sin(np.pi / 2), 0] + [0.0] * 34)

action:
  bound_lower: -torch.tensor([
    2.81706,
    1.9444,
    2.81706,
    1.9444,
    2.81706,
    1.9444,
    2.90433,
    2.81706,
    1.9444,
    2.81706,
    1.9444,
    2.81706,
    1.9444,
    2.90433])
  bound_upper: -self.action_bound_lower
  range: ([6.0] * 14)

reward:
  distance_scaling: torch.cat((torch.tensor([1, 1, 0.05, 2, 2, 2]), torch.zeros(34)))

vis:
  indices: ([5, 1 ,2])
  scale: ([2 / np.pi, 1, 1])

planner:
  single_goal:
    steps_per_goal: 1000
    reward:
      proximity_scaling: ([0.1 / 42.0] * 42)

  multi_goal:
    intermediate_pruning: False
    intermediate_replacement: False
    num_sub_goals: 20
    steps_per_goal: 10
    reward:
      proximity_scaling: ([0.0] * 18 + [5.0] * 3 + [0.0] * 18 + [5.0] * 3)
