# Copyright (c) 2023 Boston Dynamics AI Institute LLC. All rights reserved.

model_filename: dexterity/models/xml/scenes/legacy/box_push.xml

action:
  bound_lower: ([-5.0])
  bound_upper: ([5.0])
  range: torch.ones_like(self.action_bound_lower)

start:
  state: ([2.0, 0, 0, 0])
goal:
  state: ([5.0, 0, 0, 0])

termination_distance: 0.001

reward:
  proximity_scaling: ([0.1] * 3)
  distance_scaling: ([10, 0.001, 1, 0.001])

vis:
  filename: dexterity/models/xml/scenes/legacy/box_push.yml

planner:
  single_goal:
    action:
      types: "[AT.RANGED, AT.PROXIMITY, AT.CONTINUATION, AT.GOAL]"
      distribution: ([1, 1, 1, 1])
    steps_per_goal: 100
