# Copyright (c) 2023 Boston Dynamics AI Institute LLC. All rights reserved.

model_filename: dexterity/models/xml/scenes/legacy/cartpole.xml

action:
  bound_lower: ([-1.0])
  bound_upper: ([1.0])
  range: ([10.0])

reward:
  distance_scaling: ([2, 4, 0.5, 0.5])

start:
  state: ([0, np.pi, 0, 0])
goal:
  state: ([0.0, 0, 0, 0])

vis:
  filename: dexterity/models/xml/scenes/legacy/cartpole.yml

planner:
  single_goal:
    termination_distance: 0.001
    steps_per_goal: 1000
    action:
      types: "[AT.RANGED, AT.PROXIMITY, AT.CONTINUATION, AT.GOAL]"
