# Copyright (c) 2023 Boston Dynamics AI Institute LLC. All rights reserved.

model_filename: dexterity/models/xml/scenes/legacy/satellite.xml

action:
  bound_lower: torch.ones(3)
  bound_upper: -self.action_bound_lower
  range: torch.ones_like(self.action_bound_lower)

reward:
  distance_scaling: ([1.0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0])

start:
  state: ([1.0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0])
goal:
  state: ([0.0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0])

planner:
  single_goal:
    steps_per_goal: 2000
