# Copyright (c) 2023 Boston Dynamics AI Institute LLC. All rights reserved.

model_filename: dexterity/models/xml/scenes/legacy/spot_sitting_box.xml

action:
  bound_lower: ([-0.785398, -0.898845, -2.7929] * 2 + [-1.5, -1.0, 0.4, -0.1, -1.0, -0.1, -1.545])
  bound_upper: ([0.785398, 2.29511, -0.254801] * 2 + [1.5, -0.4, 2.7, 0.1, 0.8, 0.1, -0.05])
  range: ([0.3, 0.3, 0.3] * 2 + [0.6, 0.9, 0.9, 0.9, 0.9, 0.9, 0.9])
  types: "[AT.RANGED, AT.PROXIMITY, AT.CONTINUATION, AT.GOAL]"
  distribution: ([1, 4, 1, 4])

start:
  state: ([0.85, 0, 0.275] + [1, 0, 0, 0] + [1.0272e-01,  6.5845e-05,  3.5753e-01, 9.2061e-01, -1.3173e-04, -3.9049e-01, -3.1263e-04] + [0.5, 0.5, -1.35, -0.5, 0.5, -1.35] + [0.0, -0.9, 1.8, 0.0, 0.6, 0.0, -1.54] + [0.0] * 25)
goal:
  state: ([0.85, 0, 0.275] + [np.cos(np.pi / 4), 0, 0, np.sin(np.pi / 4)] + [1.0272e-01,  6.5845e-05,  3.5753e-01, 9.2061e-01, -1.3173e-04, -3.9049e-01, -3.1263e-04] + [0.5, 0.5, -1.35, -0.5, 0.5, -1.35] + [0.0, -0.9, 1.8, 0.0, 0.6, 0.0, -1.54] + [0.0] * 25)

reward:
  distance_scaling: torch.cat((torch.tensor([0.1, 0.1, 0.1]), 1.0 * torch.ones(3), torch.tensor([1.0, 1.0, 1.0]), 0.1 * torch.ones(3), 0.0 * torch.ones(6), 0.0 * torch.ones(7), 0.0 * torch.ones(25)))
  proximity_scaling: ([2.5] * 36)
  reachability_scaling: 1.5


planner:
  single_goal:
    parallel_extensions: 1
    intermediate_pruning: False
    intermediate_replacement: False

    finite_diff_eps: 1e-3


    callback_period: 1
    steps_per_goal: 300
    # action_steps_max: 10
