# Copyright (c) 2024 Boston Dynamics AI Institute LLC. All rights reserved.

model_filename: dexterity/models/xml/scenes/legacy/spot_box_mocap.xml

action:
  bound_lower: ([-1.5, -1.0, 0.4, -0.1, -1.0, -0.1, -1.545])
  bound_upper: ([1.5, -0.4, 2.7, 0.1, 0.8, 0.1, -0.05])
  range: ([0.6, 0.9, 1.2, 1.5, 1.5, 1.5, 1.5])

start:
  # mujoco: [box pos, box quat, spot pos, spot quat, spot arm]
  state: ([0,0,0, 1,0,0,0, 1.1, 0, 0.275, 1, 0, 0, 0, 0, -0.9, 1.8, 0.0, -0.9, 0.0, -1.54] + [0.0] * 19)
goal:
  state: ([0,0,0, 0,0,0,0, 0.5, 0.7, 0.275, np.cos(np.pi / 4), 0, 0, np.sin(np.pi / 4), 0.0, -0.9, 1.8, 0.0, -0.9, 0.0, -1.54] + [0.0] * 19)

reward:
  distance_scaling: torch.diag(torch.cat((torch.zeros(12), torch.tensor([5, 5, 0.1]), 1.0 * torch.ones(3), 0.0 * torch.ones(7), 0.0 * torch.ones(6), 0.1 * torch.ones(7))))
  proximity_scaling: 2.5
