# Copyright (c) 2023 Boston Dynamics AI Institute LLC. All rights reserved.

model_filename: dexterity/models/xml/scenes/legacy/spot_standing_box.xml

action:
  bound_lower: ([-1.5, -1.0, 0.4, -0.1, -1.0, -0.1, -1.545])
  bound_upper: ([1.5, -0.4, 2.7, 0.1, 0.8, 0.1, -0.05])
  range: ([0.6, 0.9, 1.2, 1.5, 1.5, 1.5, 1.5])
  types: "[AT.RANGED, AT.PROXIMITY, AT.CONTINUATION, AT.GOAL]"
  distribution: ([1, 4, 1, 4])

start:
  state: ([1.1, 0, 0.275, 1, 0, 0, 0, 0, -0.9, 1.8, 0.0, -0.9, 0.0, -1.54] + [0.0] * 13)
goal:
  state: ([0.5, 0.7, 0.275, np.cos(np.pi / 4), 0, 0, np.sin(np.pi / 4), 0.0, -0.9, 1.8, 0.0, -0.9, 0.0, -1.54] + [0.0] * 13)

reward:
  distance_scaling: torch.cat((torch.tensor([5, 5, 0.1]), 1.0 * torch.ones(3), 0.0 * torch.ones(7), 0.0 * torch.ones(6), 0.1 * torch.ones(7)))
  proximity_scaling: 2.5
  reachability_scaling: 1.5



parallel_extensions: 1
intermediate_pruning: False
intermediate_replacement: False

finite_diff_eps: 1e-3

callback_period: 1
steps_per_goal: 100

planner:
  primitives:
    action:
      start_mode: ActionMode.RELATIVE_TO_CURRENT_STATE # slowing IK trajectory
      end_mode: ActionMode.ABSOLUTE_ACTION # the IK expert output absolute actions
      distribution: ([0,0,0,0,1])
      types: "[AT.RANGED, AT.PROXIMITY, AT.CONTINUATION, AT.GOAL, AT.EXPERT]"
      expert_distribution: ([1])
      experts:
        - "primitive.PrimitiveSampler"
      expert_kwargs:
        - '{"actions_func": "spot_standing_box.compute_grasp_actions"}'
