# Copyright (c) 2023 Boston Dynamics AI Institute LLC. All rights reserved.

model_filename: dexterity/models/xml/scenes/legacy/spot_lying_box.xml

action:
  bound_lower: ([-0.785398, -0.898845, -2.7929] * 4)
  bound_upper: ([0.785398, 2.29511, -0.254801] * 4)
  range: ([0.3, 0.3, 0.3] * 4)
  types: "[AT.RANGED, AT.PROXIMITY, AT.CONTINUATION, AT.GOAL]"
  distribution: ([1, 4, 1, 4])

# object xyz (3) + object quat wxyz (4) + robot joint pos (12) + object vel (6) + robot joint vel (12)
start:
  state: ([-0.05, 0, 0.53] + [0.9238795, 0, 0, 0.3826834] + [0.15, 0.5, -1.35, -0.15, 0.5, -1.35] * 2 + [0.0] * 18)
goal:
  state: ([-0.05, 0, 0.53] + [0.9238795, 0, 0, -0.3826834] + [0.15, 0.5, -1.35, -0.15, 0.5, -1.35] * 2 + [0.0] * 18)

reward:
  distance_scaling: torch.cat((torch.tensor([0.1, 0.1, 0.1]), 1.0 * torch.ones(3), 0.0 * torch.ones(12), 0.0 * torch.ones(6), 0.0 * torch.ones(12)))
  proximity_scaling: ([2.5] * 15)
  reachability_scaling: 1.5

planner:
  single_goal:
    parallel_extensions: 1
    intermediate_pruning: False
    intermediate_replacement: False

    finite_diff_eps: 1e-3


    callback_period: 1
    steps_per_goal: 500
