# Copyright (c) 2023 Boston Dynamics AI Institute LLC. All rights reserved.

model_filename: dexterity/models/xml/scenes/generated/spot_tire.xml
policy_filename: locomotion.pt

seed: -1

action:
  bound_lower: ([-2, -2, -2, -2.62, -np.pi, 0, -2.79, -1.83, -2.87, -1.57])
  bound_upper: ([+2, +2, +2, np.pi, 0.52, np.pi, 2.79, 1.83, 2.87, 0])
  range: torch.ones_like(self.action_bound_lower) * 5.0
  types: "[AT.RANGED, AT.CONTINUATION]"
  distribution: ([1, 1])
  backward_speed_mag: 1.0
  processor_class: SpotWholebodyActionProcessor

start:
  state:
    - ([0, 0, 0.51]) # robot base xyz
    - ([1, 0, 0, 0]) # robot base quaternion
    - ([+0.1, 0.9, -1.5])
    - ([-0.1, 0.9, -1.5])
    - ([+0.1, 1.1, -1.5])
    - ([-0.1, 1.1, -1.5])
    - ([0.0, -0.9, 1.8, 0.0, -0.9, 0.0, 0.0]) # arm
    - ([1.1,  0, 0.3]) # object xyz
    - ([1, 0, 0, 0]) # object quaternion
    - ([0.0] * 31) # velocities
goal:
  state:
    - ([0,  0, 0.51]) # robot base xyz
    - ([1, 0, 0, 0]) # robot base quaternion
    - ([+0.1, 0.9, -1.5])
    - ([-0.1, 0.9, -1.5])
    - ([+0.1, 1.1, -1.5])
    - ([-0.1, 1.1, -1.5])
    - ([0.0, -0.9, 1.8, 0.0, -0.9, 0.0, 0.0]) # arm
    - ([2.0,  1.0, 0.3]) # object xyz
    - ([1, 0, 0, 0]) # object quaternion
    - ([0.0] * 31) # velocities

reward:
  distance_scaling:
    - ([0.0] * 3) # base xyz
    - ([0.0] * 3) # base rot
    - ([0.0] * 12) # legs
    - ([0.0] * 7) # arm
    - ([10.0] * 3) # object xyz
    - ([0.0] * 3) # object rot
    - ([1.0] * 3) # robot base: linear velocities
    - ([1.0] * 3) # robot base: angular velocities
    - ([0.0] * 12) # robot legs: joint velocities
    - ([0.0] * 7) # robot arm: joint velocities
    - ([1.0] * 3) # object: linear velocity
    - ([1.0] * 3) # object: angular velocity

  proximity_scaling:
    - ([-1.0] * 3) # base <-> object
    - ([0.0] * 18) # arm <-> object
    - ([1.0] * 3) # end-effector <-> object
    - ([0.0] * 3) # tire y-axis
    - ([0.0] * 12) # last_action (always last)

  reachability_scaling: 1.5

termination_distance: 0.0

early_termination_fns:
  - "is_object_tilted"
  - "is_object_out_of_reach"
  - "torso_too_close_to_object"

num_sub_goals: 10
steps_per_goal: 30
parallel_extensions: 10

learner:
  trajectory_length: 40
