# Copyright (c) 2023 Boston Dynamics AI Institute LLC. All rights reserved.

model_filename: "spot_bimanual_stool.xml"
vis:
  filename: "spot_bimanual_stool.yml"
  q_indices: ([7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 3, 4, 5, 6, 0, 1, 2])
  scale: ([1, 1, 1])
  indices: ([0, 1, 2])

action:
  bound_lower: ([-0.7, -1.0, 0.1, -0.1, -1.5, -0.1, -0.05] * 2)
  bound_upper: ([0.7, 0.05, 2.0, 0.1, 1.5, 0.1, -0.05] * 2)
  range: ([0.2, 0.4, 0.5, 0.6, 0.7, 0.7, 0.7] * 2)
  types: ([AT.RANGED, AT.PROXIMITY, AT.CONTINUATION, AT.GRADIENT])
  distribution: ([1, 1, 1, 1])

reward:
  distance_scaling: torch.diag(torch.tensor([1, 1, 1, 2, 2, 0] + [0] * 14 + [0.1] * 6 + [0] * 14))
  proximity_scaling: 1.0
  reachability_scaling: 0.1

start:
  state:       ([ 0.0,  0.0, 0.15, np.cos(np.pi/4), 0, np.sin(np.pi/4), 0] + [0, -0.1, 1.4, 0.0, -0.5, 0.0, -0.05] * 2 + [0.0] * 20)
  bound_lower: ([-0.2, -0.2, 0.15, np.cos(np.pi/4), 0, np.sin(np.pi/4), 0] + [0, -0.5, 2.0, 0.0, -0.0, 0.0, -0.05] * 2 + [0.0] * 20)
  bound_upper: ([ 0.2,  0.2, 0.15, np.cos(np.pi/4), 0, np.sin(np.pi/4), 0] + [0, -0.5, 2.0, 0.0, -0.0, 0.0, -0.05] * 2 + [0.0] * 20)


goal:
  state:       ([ 0.0,  0.0, 0.4325, 1, 0, 0, 0] + [0, -0.5, 2.0, 0.0, -0.0, 0.0, -0.05] * 2 + [0.0] * 20)
  bound_lower: ([-0.2, -0.2, 0.4325, 1, 0, 0, 0] + [0, -0.5, 2.0, 0.0, -0.0, 0.0, -0.05] * 2 + [0.0] * 20)
  bound_upper: ([ 0.2,  0.2, 0.4325, 1, 0, 0, 0] + [0, -0.5, 2.0, 0.0, -0.0, 0.0, -0.05] * 2 + [0.0] * 20)

learner:
  early_stop: 1.0
  trajectory_length: 75
  use_planner_exploration: False
  stop_converged_random_exploration: False
  use_sparse_reward: True
  initial_success_distance: 0.2
  final_success_distance: 0.2
  her_probability: 0.0
  stop_converged_injection: False
  max_initial_injections: 100
  max_planner_experience_share: 0.25
  injection_strategy: 1

ignore_sampled_state_collisions: True
intermediate_pruning: False
num_sub_goals: 30
steps_per_goal: 30
goal_bias: 0.0
termination_distance: 0.2
max_main_nodes: 50000
action_time_step: 0.4
action_steps_max: 3

seed: 0
