# Copyright (c) 2023 Boston Dynamics AI Institute LLC. All rights reserved.

model_filename: "spot_lying_ball.xml"
vis:
  filename: "spot_lying_ball.yml"
  q_indices: ([7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 3, 4, 5, 6, 0, 1, 2])

action:
  bound_lower: ([-0.5, -0.5, -2.5] * 4)
  bound_upper: ([0.5, 2.0, 0.5] * 4)
  range: ([0.4, 0.4, 0.4] * 4)
  types: "[AT.RANGED, AT.PROXIMITY, AT.CONTINUATION, AT.GRADIENT]"
  distribution: ([2, 3, 1, 3])

reward:
  distance_scaling: torch.diag(torch.tensor([1, 1, 1, 2, 2, 0] + [0] * 12 + [0.1,0.1,0.1,0.1,0.1,0.1] + [0] *12))
  proximity_scaling: 0.1
  reachability_scaling: 0.1

# object xyz (3) + object quat wxyz (4) + robot joint pos (12) + object vel (6) + robot joint vel (12)
start:
  state:       ([0, 0, 0.7] + [np.cos(np.pi/4), 0,  np.sin(np.pi/4), 0] + [0.45, 1.0, -1.5, -0.45, 1.0, -1.5, 0.3, 0.6, -1.35, -0.3, 0.6, -1.35] + [0.0] * 18)
  bound_lower: ([0, 0, 0.7] + [              0, 0, -1, 0] + [0.45, 1.0, -1.5, -0.45, 1.0, -1.5, 0.3, 0.6, -1.35, -0.3, 0.6, -1.35] + [0.0] * 18)
  bound_upper: ([0, 0, 0.7] + [np.cos(np.pi/4), 0,  1, 0] + [0.45, 1.0, -1.5, -0.45, 1.0, -1.5, 0.3, 0.6, -1.35, -0.3, 0.6, -1.35] + [0.0] * 18)
goal:
  state:       ([   0,    0, 0.7] + [1, 0, 0, 0] + [0.45, 1.0, -1.5, -0.45, 1.0, -1.5, 0.3, 0.6, -1.35, -0.3, 0.6, -1.35] + [0.0] * 18)
  bound_lower: ([ 0.1, -0.1, 0.7] + [1, 0, 0, 0] + [0.45, 1.0, -1.5, -0.45, 1.0, -1.5, 0.3, 0.6, -1.35, -0.3, 0.6, -1.35] + [0.0] * 18)
  bound_upper: ([-0.1,  0.1, 0.9] + [1, 0, 0, 0] + [0.45, 1.0, -1.5, -0.45, 1.0, -1.5, 0.3, 0.6, -1.35, -0.3, 0.6, -1.35] + [0.0] * 18)

learner:
  early_stop: 1.0
  trajectory_length: 75
  use_planner_exploration: False
  stop_converged_random_exploration: False
  use_sparse_reward: True
  initial_success_distance: 0.2
  final_success_distance: 0.2
  her_probability: 0.0
  stop_converged_injection: False
  max_initial_injections: 100
  max_planner_experience_share: 0.25
  injection_strategy: 1

ignore_sampled_state_collisions: True
intermediate_pruning: False
num_sub_goals: 30
steps_per_goal: 30
goal_bias: 0.0
termination_distance: 0.2
max_main_nodes: 50000
action_time_step: 0.4
action_steps_max: 3

seed: 0
